### ISSUE TITLE
Unable to run SiMo on Ubuntu

### ISSUE THREAD

**Issue by verenich** [AdaptiveBProcess/Simod#1]
Running `python simo.py` on Ubuntu 16.04 produces the following error:

```
 -- Mining Process Structure --
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to load required SO
        at com.raffaeleconforti.benchmark.BenchmarkCommandline.loadLibLinux(BenchmarkCommandline.java:120)
        at com.raffaeleconforti.benchmark.BenchmarkCommandline.loadFromJar(BenchmarkCommandline.java:71)
        at com.raffaeleconforti.benchmark.BenchmarkCommandline.<clinit>(BenchmarkCommandline.java:56)
Caused by: java.lang.NullPointerException
        at org.apache.poi.util.IOUtils.copy(IOUtils.java:182)
        at com.raffaeleconforti.benchmark.BenchmarkCommandline.loadLibLinux(BenchmarkCommandline.java:116)
        ... 2 more
```

**Comment by Mcamargo85** [comment]
This issue was solved in the last version of the tool.
